/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: benicourt (https://sketchfab.com/benicourt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-mission-to-mars-034f22a9c08940f282f3960d2cf45c22
Title: Astronaut : Mission to Mars
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Astronaut(props) {
  
  const { nodes, materials, animations } = useGLTF('/models/walkastro.glb')
  

  const modelRef = useRef()

  useFrame((state, delta, xrFrame ) => {
    console.log(state.clock)
    modelRef.current.position.y = -1.3 + Math.sin(state.clock.elapsedTime)*0.15;
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef} 
    position={[0,-1.3,0]}
    scale={[1.45,1.45,1.45]}
    rotation={[0,0.4,0]}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials['Scene_-_Root']}
          skeleton={nodes.Object_7.skeleton}
          scale={0.004}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/walkastro.glb')