/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Antropik (https://sketchfab.com/Antropik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-482bf87662fd4b378bcb3a2931d59ca3
Title: astronaut
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Astro(props) {
  const modelRef = useRef()
  const { nodes, materials, animations } = useGLTF('/models/astronaut.glb')
  
  useFrame(() => {
    modelRef.current.rotation.y += 0.007
  })

  return (
    <group ref={modelRef} {...props} dispose={null}
    scale={[2,2,2]}
    position={[0.5,-1.5,0]}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.astronaut}
          skeleton={nodes.Object_10.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.027}
        />
        <skinnedMesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.astronaut}
          skeleton={nodes.Object_12.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.027}
        />
        <skinnedMesh
          name="Object_122"
          geometry={nodes.Object_122.geometry}
          material={materials.astronaut}
          skeleton={nodes.Object_122.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.027}
        />
        <skinnedMesh
          name="Object_124"
          geometry={nodes.Object_124.geometry}
          material={materials.astronaut}
          skeleton={nodes.Object_124.skeleton}
          morphTargetDictionary={nodes.Object_124.morphTargetDictionary}
          morphTargetInfluences={nodes.Object_124.morphTargetInfluences}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.027}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/astronaut.glb')