/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pnhtuan (https://sketchfab.com/pnhtuan7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-rocket-a6b881c9b1674c6bb77240ae8b2b8696
Title: old rocket
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Rocket(props) {
  const { nodes, materials } = useGLTF('/models/rocket.glb')

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007
  })

  return (
    <group {...props} dispose={null} ref={modelRef} scale={[9,9,9]} rotation={[0.4,0,-0.4]} position={[0,1,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_Body1_0.geometry}
        material={materials.Body1}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.C_old1_C_old_0.geometry}
        material={materials.C_old}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Green_Green_old_0.geometry}
        material={materials.Green_old}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gold1_Gold_0.geometry}
        material={materials.Gold}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Red_Red_old_0.geometry}
        material={materials.Red_old}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/rocket.glb')